### PR TITLE
feat: add support for Import Attributes and RegExp Modifiers

### PR DESCRIPTION
**Pull request by ota-meshi**
#### Prerequisites checklist

-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).

#### What is the purpose of this pull request?

Add support for ES2025 import attributes, and add support for RegExp modifiers.

#### What changes did you make? (Give an overview)

This PR adds support for ES2025 import attributes and RegExp modifiers.

#### Related Issues

Related to https://github.com/eslint/eslint/issues/19014, https://github.com/eslint/eslint/issues/19073

### CODE REVIEW

**Review by nzakas — APPROVED** [review]
LGTM. Waiting for another approval before merging.

**Review by mdjermanovic — COMMENTED** [review]
Are there any changes to `eslint-scope` needed?

If not, can you just add a few tests to confirm? For example:

```js
const type = "json";

import pkg from "./package.json" with { type: "json" }; // not a reference to `type`

export * from "./package.json" with { type: "json" }; // not a reference to `type`

export { default } from "./package.json" with { type: "json" }; // not a reference to `type`

import("./package.json", { with: { type } }); // a reference to `type`

```

**Comment by ota-meshi** [comment]
Thank you for the review!
I didn't notice that. I will test it and fix it 😄

**Comment by ota-meshi** [comment]
I added test cases to eslint-scope.
However, eslint-scope seems to work fine already, probably because the ImportAttribute node's visitor is not defined, so it doesn't get processed.

**Review by mdjermanovic — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
